// POST /api/review
//
// Accepts the review request and returns a UX review generated by Claude.
// All Anthropic code lives in ../anthropic-review.js — this file only validates
// the request and maps errors to HTTP responses.
//
// Expected request body — at least ONE of the three design inputs is required:
//   {
//     projectName: string,
//     description: string,
//     task:        string,
//     persona:     { name, role, experience, domain, tech, goal, accessibility },
//     methods:     { synthetic: boolean, heuristic: boolean },
//     screenshots:    [{ name, src }],                                  // analyzed by Claude (vision)
//     prototypeVideo: { name, mediaType, duration, src } | null,       // accepted + stored; not analyzed yet
//     prototypeUrl:   string | null                                    // validated + passed through; not navigated yet
//   }
import { Router } from 'express';
import { buildReviewWithClaude } from '../anthropic-review.js';

const router = Router();

router.post('/', async (req, res) => {
  const body = req.body || {};
  const { projectName, task, methods, screenshots, prototypeVideo, prototypeUrl } = body;

  // Minimal validation of the fields the review depends on.
  if (!projectName || !task) {
    return res.status(400).json({ error: 'projectName and task are required.' });
  }
  if (!methods || (!methods.synthetic && !methods.heuristic)) {
    return res.status(400).json({ error: 'Select at least one review method.' });
  }
  const hasScreens = Array.isArray(screenshots) && screenshots.length > 0;
  const hasVideo = prototypeVideo && typeof prototypeVideo === 'object' && typeof prototypeVideo.src === 'string';
  const hasUrl = typeof prototypeUrl === 'string' && /^https?:\/\/\S+\.\S+/.test(prototypeUrl);
  if (!hasScreens && !hasVideo && !hasUrl) {
    return res.status(400).json({ error: 'Add at least one design input — screenshots, a prototype recording, or a prototype URL.' });
  }

  try {
    const report = await buildReviewWithClaude(body);
    res.json(report);
  } catch (err) {
    console.error('[/api/review] failed:', err);
    if (err.code === 'NO_API_KEY') {
      return res.status(503).json({ error: 'Server is not configured with an ANTHROPIC_API_KEY.' });
    }
    if (err.code === 'REFUSAL') {
      return res.status(502).json({ error: err.message });
    }
    // JSON parse failure, validation failure, or an API/network error.
    return res.status(502).json({ error: 'The review could not be generated. Please try again.' });
  }
});

export default router;
