// Real UX review, generated by Claude. This is the ONLY file that talks to
// Anthropic — everything else (the route, the frontend) is provider-agnostic.
//
// INPUT (same documented shape the endpoint accepts):
//   { projectName, description, task,
//     persona: { name, role, experience, domain, tech, goal, accessibility },
//     methods: { synthetic, heuristic },
//     screenshots:    [{ name, src }],                            // sent to Claude as images
//     prototypeVideo: { name, mediaType, duration, src } | null,  // NOT analyzed yet — the
//                        // Claude API accepts images only, so the recording is described to
//                        // the model by metadata. When video support (or a frame-extraction
//                        // step) lands, convert it to image blocks inside buildUserContent
//                        // without touching the API contract.
//     prototypeUrl:   string | null }                             // NOT navigated yet — passed
//                        // as context only. A future Playwright step can capture screenshots
//                        // from it and feed them into the same screenshots pipeline.
//
// OUTPUT: the structured report described in SCHEMA_DOC below, validated before
// it is returned to the caller.
import Anthropic from '@anthropic-ai/sdk';

// --- Tunables (safe to change) ---------------------------------------------
const MODEL = 'claude-opus-5';   // vision-capable; swap to 'claude-sonnet-5' to cut cost
const EFFORT = 'high';           // low | medium | high | xhigh | max
const MAX_TOKENS = 16000;
const MAX_IMAGES = 100;          // uploads are uncapped; 100 is Claude's practical per-request image limit
const SUPPORTED_MEDIA = ['image/png', 'image/jpeg', 'image/webp'];

// Claude 4/5 image understanding does not accept SVG. Sample screens ship as
// SVG data URLs, so they're described by name only rather than sent as images.

const SYSTEM_PROMPT = `You are a senior UX researcher producing a structured usability review of a product's user journey from interface screenshots.

Conduct two evaluations, using ONLY what is visible in the provided screenshots and text:
1. A synthetic-user walkthrough: simulate how the described persona attempts the primary task, screen by screen, in the given journey order.
2. A UX heuristic evaluation against Nielsen's ten usability heuristics.

Rules you must follow:
- These are AI-generated hypotheses. NEVER claim that real users were tested or observed. Write about what a user "would likely" do, not what they "did".
- Base every finding on visible evidence. If something cannot be determined from a static screenshot (interaction behavior, loading states, keyboard accessibility, error handling, motion), mark the relevant heuristic status as "Not observable" and do not invent findings about it.
- Return between 3 and 8 findings, most severe first.
- Respond with a SINGLE JSON object and nothing else — no prose, no markdown code fences.`;

// Human-readable schema handed to the model (JSON Schema constraints like
// enums are also re-checked in validateReport below).
const SCHEMA_DOC = `Return a JSON object with EXACTLY these keys:

{
  "executiveSummary": string,            // 2-4 sentences: overall experience, strengths, key risks, likely task outcome
  "overallScore": number,                // overall usability score, 0-100
  "strengths": string[],                 // major strengths
  "keyRisks": string[],                  // key usability risks
  "likelyOutcome": string,               // one sentence: Success / Hesitation / Failure and why
  "findings": [{
    "title": string,
    "description": string,               // what the issue is and its user impact
    "category": string,                  // e.g. "Navigation & wayfinding", "Content clarity", "Accessibility"
    "source": "Synthetic User" | "UX Heuristic" | "Both",
    "severity": "Critical" | "High" | "Medium" | "Low",
    "confidence": number,                // 0.0-1.0
    "screenReference": string,           // the exact screen name this refers to
    "evidence": string,                  // what is visible in the screenshot that supports this
    "recommendation": string             // one concrete, actionable change
  }],
  "syntheticJourney": [{                  // one entry per screen, in journey order
    "screenReference": string,
    "expectedAction": string,
    "syntheticReaction": string,         // first-person, in quotes, from the persona's perspective
    "outcome": "Success" | "Hesitation" | "Failure",
    "relatedFindings": string[]          // titles of related findings above
  }],
  "syntheticObservations": {
    "expectations": string[],
    "questions": string[],
    "hesitations": string[],
    "decisionPoints": string[]
  },
  "heuristicSummary": [{
    "heuristic": string,
    "status": "Pass" | "Warning" | "Violation" | "Not observable",
    "note": string
  }],
  "recommendedActions": [{
    "change": string,
    "rationale": string,
    "expectedImpact": string,
    "priority": "P0" | "P1" | "P2",
    "relatedFinding": string             // title of the related finding
  }],
  "limitations": string[]                // caveats about this AI-generated report
}

If the user selected only one review method, still return every key: leave the
other method's array empty (e.g. an empty "heuristicSummary" if only the
synthetic review was requested).`;

// Describes which design inputs exist and how the model may use each. Video
// and URL are context-only for now: this is the single place to upgrade when
// video analysis or URL capture (Playwright) is added later.
function describeDesignInputs({ screenshots, prototypeVideo, prototypeUrl }) {
  const parts = [];
  if (screenshots.length) {
    const names = screenshots.map((s, i) => `${i + 1}. ${s.name || 'Screen ' + (i + 1)}`).join('\n');
    parts.push(`## Screenshot journey (${screenshots.length} screens, in order)\n${names}\nThe screenshots follow after this brief. Screens listed without an attached image were provided as vector placeholders — reason about them from their name and position in the journey.`);
  }
  if (prototypeVideo) {
    const dur = typeof prototypeVideo.duration === 'number' ? `${Math.round(prototypeVideo.duration)}s` : 'unknown duration';
    parts.push(`## Prototype recording (metadata only)\n"${prototypeVideo.name}" (${prototypeVideo.mediaType || 'video'}, ${dur}). You CANNOT watch this recording — do not invent observations from it. Mention in "limitations" that the recording was provided but not analyzed.`);
  }
  if (prototypeUrl) {
    parts.push(`## Prototype link (reference only)\n${prototypeUrl}\nYou CANNOT open URLs — do not invent observations about this prototype. Mention in "limitations" that the link was provided but not navigated.`);
  }
  if (!screenshots.length) {
    parts.push(`## No screenshots provided\nBase the review on the product description, task, and persona alone. Use "Overall flow" as the screenReference, keep confidence values low, and mark heuristics that need visual evidence as "Not observable".`);
  }
  return parts.join('\n\n');
}

function buildUserContent(input) {
  const { projectName, description, task, persona = {}, methods = {}, screenshots = [], prototypeVideo = null, prototypeUrl = null } = input;

  const methodList = [
    methods.synthetic && 'Synthetic User Review',
    methods.heuristic && 'UX Heuristic Evaluation',
  ].filter(Boolean).join(', ') || 'Synthetic User Review';

  const intro = `# Project
Name: ${projectName}
Description: ${description || '(none provided)'}
Primary user task to evaluate: ${task}

# Persona
Name: ${persona.name || '(unnamed)'}
Role / user type: ${persona.role || '(unspecified)'}
Experience level: ${persona.experience || '(unspecified)'}
Domain knowledge: ${persona.domain || '(unspecified)'}
Technology proficiency: ${persona.tech || '(unspecified)'}
Primary goal: ${persona.goal || '(unspecified)'}
Accessibility considerations: ${persona.accessibility || '(none)'}

# Review methods requested
${methodList}

# Design inputs
${describeDesignInputs({ screenshots, prototypeVideo, prototypeUrl })}

${SCHEMA_DOC}`;

  const content = [{ type: 'text', text: intro }];

  let attached = 0;
  screenshots.forEach((s, i) => {
    if (attached >= MAX_IMAGES) return;
    const m = /^data:(.+?);base64,(.+)$/.exec(s.src || '');
    if (!m) return;
    const mediaType = m[1].toLowerCase();
    if (!SUPPORTED_MEDIA.includes(mediaType)) return;
    content.push({ type: 'text', text: `Screen ${i + 1}: ${s.name || 'Screen ' + (i + 1)}` });
    content.push({ type: 'image', source: { type: 'base64', media_type: mediaType, data: m[2] } });
    attached++;
  });

  return content;
}

// Pull the JSON object out of the model's text, tolerating code fences.
function extractJson(text) {
  let t = (text || '').trim();
  const fence = /```(?:json)?\s*([\s\S]*?)```/i.exec(t);
  if (fence) t = fence[1].trim();
  const first = t.indexOf('{');
  const last = t.lastIndexOf('}');
  if (first !== -1 && last > first) t = t.slice(first, last + 1);
  return JSON.parse(t);
}

const SEVERITIES = ['Critical', 'High', 'Medium', 'Low'];
const SOURCES = ['Synthetic User', 'UX Heuristic', 'Both'];

// Validate the AI response before it reaches the frontend. Throws on anything
// the report page can't safely render.
function validateReport(r) {
  const fail = (msg) => { throw new Error('Invalid AI response: ' + msg); };
  if (!r || typeof r !== 'object') fail('not an object');
  if (typeof r.executiveSummary !== 'string' || !r.executiveSummary.trim()) fail('executiveSummary missing');
  if (typeof r.overallScore !== 'number' || r.overallScore < 0 || r.overallScore > 100) fail('overallScore out of range');
  if (!Array.isArray(r.findings) || r.findings.length === 0) fail('findings missing');

  r.findings.forEach((f, i) => {
    const where = `findings[${i}]`;
    if (!f || typeof f !== 'object') fail(where + ' not an object');
    ['title', 'description', 'category', 'screenReference', 'evidence', 'recommendation'].forEach((k) => {
      if (typeof f[k] !== 'string' || !f[k].trim()) fail(`${where}.${k} missing`);
    });
    if (!SEVERITIES.includes(f.severity)) fail(`${where}.severity invalid`);
    if (!SOURCES.includes(f.source)) fail(`${where}.source invalid`);
    if (typeof f.confidence !== 'number' || f.confidence < 0 || f.confidence > 1) fail(`${where}.confidence invalid`);
  });

  // These arrays/objects are optional in practice but must be the right type if present.
  ['strengths', 'keyRisks', 'syntheticJourney', 'heuristicSummary', 'recommendedActions', 'limitations'].forEach((k) => {
    if (r[k] != null && !Array.isArray(r[k])) fail(`${k} must be an array`);
  });
  return r;
}

export async function buildReviewWithClaude(input) {
  if (!process.env.ANTHROPIC_API_KEY) {
    const err = new Error('ANTHROPIC_API_KEY is not set on the server.');
    err.code = 'NO_API_KEY';
    throw err;
  }

  const client = new Anthropic(); // reads ANTHROPIC_API_KEY from the environment

  // Streaming avoids HTTP timeouts on longer vision + reasoning requests.
  const stream = client.messages.stream({
    model: MODEL,
    max_tokens: MAX_TOKENS,
    system: SYSTEM_PROMPT,
    output_config: { effort: EFFORT },
    messages: [{ role: 'user', content: buildUserContent(input) }],
  });
  const message = await stream.finalMessage();

  if (message.stop_reason === 'refusal') {
    const err = new Error('The model declined to review these screenshots.');
    err.code = 'REFUSAL';
    throw err;
  }

  // Thinking blocks (on by default for Opus 5) precede the text block.
  const text = message.content
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('\n');

  const report = extractJson(text); // throws SyntaxError if not valid JSON
  return validateReport(report);
}
